default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: development
  username: postgres
  password: AlexPass
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: test
  username: postgres
  password: AlexPass
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: production
  username: postgres
  password: AlexPass
  host: localhost
  encoding: UTF8