default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: samanage_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  strict: false

development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: samanage_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  strict: false

production:
  adapter: postgresql
  database: production
  username: postgres
  password: AlexPass
  host: localhost
  encoding: UTF8